### ISSUE TITLE
Project #2

### ISSUE THREAD

**Issue by brissettdwayne** [brissettdwayne/rest_app#1]
https://github.com/brissettdwayne/rest_app

Whenever I click my add food or add customer button, I keep getting this error "No route matches {:action=>"new", :controller=>"orders"} missing required keys: [:table_id]."

I'm not 100% sure how to go about fixing this.

The error is happening in the /Users/dwaynebrissett/Desktop/wdi/rest_app/app/views/customers/new.html.erb file

**Comment by rapala61** [comment]
The key is the error message:  `missing required keys: [:table_id].`

The `new_table_order_path` expects you to tell it which table should be the order associated with, hence it asks for a @table id. This is because its a nested resource route, like: /tables/:table_id/orders/new

Try changing this:
```
<%= button_to "Orders", new_table_order_path, method: :get %>
```
To:

```
<%= button_to "Orders", new_table_order_path(@table), method: :get %>
```

This @table variable should be table that the new order would be associated with

**Comment by rapala61** [comment]
Was this helpful?

**Comment by brissettdwayne** [comment]
Yes it did. Thank you very much for your help.
